/*
Replaces Schedule:Compact with schedule:File objects

Purpose:
This DesignBuilder C# script replaces one or more Schedule:Compact objects with Schedule:File objects
in the EnergyPlus IDF generated by DesignBuilder.

Main Steps:
For each configured schedule name:
1) Find the Schedule:Compact object (acts as the required placeholder)
2) Create an equivalent Schedule:File object (from a user-specified CSV file/column)
3) Load the new Schedule:File object into the IDF
4) Remove the original Schedule:Compact object
Save the modified IDF before EnergyPlus simulation starts

How to Use:

Configuration
- Add one or more ReplaceCompactSchedule(...) calls in BeforeEnergySimulation().
- For each call, set:
  - scheduleName: Name of the existing Schedule:Compact object to replace (placeholder name in the IDF)
  - filePath: Full path to the schedule CSV/text file to be used by Schedule:File
  - columnNumber: Which column contains the schedule values (1 = first column)
  - rowsToSkip: Header rows to skip before data begins
  - columnSeparator (optional): e.g. "comma", "tab", "fixed", or "semicolon" (default is "comma")
NOTE: EnergyPlus is case-insensitive for many keywords, but matching standard casing is recommended.

Prerequisites / Placeholders
- The base model must contain a Schedule:Compact object with the exact name passed into ReplaceCompactSchedule(...).

DISCLAIMER: This script is provided as-is without warranty. DesignBuilder takes no responsibility for simulation results, accuracy, or any issues arising from the use of this script. 
Users are responsible for validating all outputs and ensuring the script meets their specific modeling requirements.
*/

using System.Linq;
using System;
using DB.Extensibility.Contracts;
using EpNet;

namespace DB.Extensibility.Scripts
{
    public class IdfFindAndReplace : ScriptBase, IScript
    {
        private IdfReader idfReader;

        public override void BeforeEnergySimulation()
        {
            idfReader = new IdfReader(
                ApiEnvironment.EnergyPlusInputIdfPath,
                ApiEnvironment.EnergyPlusInputIddPath);

            // ----------------------------
            // USER CONFIGURATION SECTION
            // ----------------------------
            // Define schedules to be replaced (repeat this call for each schedule)
            ReplaceCompactSchedule(
                scheduleName: "test schedule",             // Name of existing Schedule:Compact (placeholder)
                filePath: @"C:\path\to\your\file.csv",     // Path to Schedule:File
                columnNumber: 1,
                rowsToSkip: 0);

            idfReader.Save();
        }

        public IdfObject FindObject(string objectType, string objectName)
        {
            try
            {
                return idfReader[objectType].First(c => c[0] == objectName);
            }
            catch (Exception)
            {
                throw new Exception(String.Format("Cannot find object: {0}, type: {1}", objectName, objectType));
            }
        }

        public void ReplaceCompactSchedule(string scheduleName, string filePath, int columnNumber, int rowsToSkip, string columnSeparator = "comma")
        {
            IdfObject schedule = FindObject("Schedule:Compact", scheduleName);
            string scheduleFileIdfText = BuildScheduleFile(scheduleName, filePath, columnNumber, rowsToSkip, columnSeparator);

            // Add the new Schedule:File object, then remove the old Schedule:Compact object
            idfReader.Load(scheduleFileIdfText);
            idfReader.Remove(schedule);
        }

        public string BuildScheduleFile(string scheduleName, string filePath, int columnNumber, int rowsToSkip, string columnSeparator)
        {
            // Builds the IDF text for a Schedule:File object using the provided parameters.
            string scheduleTemplate = @"Schedule:File,
  {0},                !- Name
  Any Number,         !- Schedule Type Limits Name
  {1},                !- File Name
  {2},                !- Column Number
  {3},                !- Rows to Skip at Top
  8760,               !- Number of Hours of Data
  {4},                !- Column Separator
  ,                   !- Interpolate to Timestep
  60;                 !- Minutes per Item";

            return String.Format(scheduleTemplate, scheduleName, filePath, columnNumber, rowsToSkip, columnSeparator);
        }
    }
}